// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcsnxswekhjirzvnshzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjc254c3dla2hqaXJ6dm5zaHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTQ2NTQsImV4cCI6MjA3MTA3MDY1NH0.750ewphwFdaiE-De57hYk7Id_SzJlkAlqE-ARGrMdc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});